/*
 * Stolen from cpython.
 */
#include "pyhead.h"
#include <marshal.h>

#include <stdio.h>
#include "file_util.h"
#include "mallocator.h"
#include "log_print.h"

#define auto __auto_type
/* To avoid a circular dependency on frozen.o, we create our own structure
   of frozen modules instead, left deliberately blank so as to avoid
   unintentional import of a stale version of _frozen_importlib. */

static const struct _frozen _PyImport_FrozenModules[] = {
    {0, 0, 0} /* sentinel */
};
#ifndef _WIN32
/* On Windows, this links with the regular pythonXY.dll, so this variable comes
   from frozen.obj. In the Makefile, frozen.o is not linked into this executable,
   so we define the variable here. */
const struct _frozen *PyImport_FrozenModules;
#endif

static const char header[] =
    "/* Auto-generated by PythonEmbed/freeze_py_module.c */\n"
    "#if (PY_MINOR_VERSION != " STRINGIFY(PY_MINOR_VERSION)") || (PY_MAJOR_VERSION != " STRINGIFY(PY_MAJOR_VERSION)")\n"
    "#error \"Python versions mismatch - clear the frozen headers\"\n"
    "#endif\n";

int
main(int argc, char *argv[])
{
    const char *name, *inpath, *outpath;
    FILE *outfile = NULL;
    PyObject *code = NULL, *marshalled = NULL;

    PyImport_FrozenModules = _PyImport_FrozenModules;

    if(argc != 4) {
        fprintf(stderr, "usage: %s modulename python_input header_output\n", argc?argv[0]:"");
        return 2;
    }
    name = argv[1];
    inpath = argv[2];
    outpath = argv[3];
    auto insource = read_file(inpath, get_mallocator());
    if(insource.errored){
        fprintf(stderr, "cannot open '%s' for reading\n", inpath);
        goto error;
        }
    auto text = insource.result;

#if PY_MINOR_VERSION > 7
    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);

    config.site_import = 0;

    PyStatus status;
    status = PyConfig_SetString(&config, &config.program_name,
                                L"./freeze_py_module");
    if (PyStatus_Exception(status)) {
        PyConfig_Clear(&config);
        fprintf(stderr, "status is bad\n");
        Py_ExitStatusException(status);
    }
    /* Don't install importlib, since it could execute outdated bytecode. */
    config._install_importlib = 0;
    config._init_main = 0;

    status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) {
        fprintf(stderr, "status is bad\n");
        Py_ExitStatusException(status);
    }
#else
    // Our vendored stdlib is for 3.8 or later
    outfile = fopen(outpath, "w");
    if (outfile == NULL) {
        fprintf(stderr, "cannot open '%s' for writing\n", outpath);
        goto error;
    }
    fprintf(outfile, "%s\n", header);
    fflush(outfile);
    fclose(outfile);
    return 0;

    _PyCoreConfig config = _PyCoreConfig_INIT;
    config.program_name = L"./_freeze_importlib";
    /* Don't install importlib, since it could execute outdated bytecode. */
    config._disable_importlib = 1;

    Py_NoUserSiteDirectory++;
    Py_NoSiteFlag++;
    Py_IgnoreEnvironmentFlag++;
    Py_FrozenFlag++;


    _PyInitError err = _Py_InitializeFromConfig(&config);
    /* No need to call _PyCoreConfig_Clear() since we didn't allocate any
       memory: program_name is a constant string. */
    if (_Py_INIT_FAILED(err)) {
        _Py_FatalInitError(err);
    }
#endif

    {
    char buf[100];
    snprintf(buf, sizeof(buf), "<frozen %s>", name);
    code = Py_CompileStringExFlags(text.text, buf, Py_file_input, NULL, 2);
    if(code == NULL){
        ERROR("code is NULL (%p)\n", code);
        PyErr_Print();
        goto error;
        }
    }

    marshalled = PyMarshal_WriteObjectToString(code, Py_MARSHAL_VERSION);
    Py_CLEAR(code);
    if (marshalled == NULL){
        fprintf(stderr, "marshalled is NULL\n");
        PyErr_Print();
        goto error;
        }

    unhandled_error_condition(!PyBytes_CheckExact(marshalled));
    auto data = (unsigned char *) PyBytes_AS_STRING(marshalled);
    size_t data_size = PyBytes_GET_SIZE(marshalled);

    /* Open the file in text mode. The hg checkout should be using the eol extension,
       which in turn should cause the EOL style match the C library's text mode */
    outfile = fopen(outpath, "w");
    if (outfile == NULL) {
        fprintf(stderr, "cannot open '%s' for writing\n", outpath);
        goto error;
    }
    fprintf(outfile, "%s\n", header);
    {
    char buf[100];
    size_t n = 0;
    for (size_t i = 0; name[i] != '\0'; i++) {
        if (name[i] != '.') {
            buf[n++] = name[i];
        }
    }
    buf[n] = '\0';
    fprintf(outfile, "static const unsigned char _Py_M__%s[] = {\n", buf);
    }
    for (size_t n = 0; n < data_size; n += 16) {
        size_t end = Py_MIN(n + 16, data_size);
        fprintf(outfile, "    ");
        for (size_t i = n; i < end; i++) {
            fprintf(outfile, "%u,", (unsigned int) data[i]);
        }
        fprintf(outfile, "\n");
    }
    fprintf(outfile, "};\n");

    Py_CLEAR(marshalled);

    Py_Finalize();
    if (outfile) {
        if (ferror(outfile)) {
            fprintf(stderr, "error when writing to '%s'\n", outpath);
            goto error;
        }
        fclose(outfile);
    }
    return 0;

error:
    fprintf(stderr, "Failed to freeze '%s'\n", argv[3]);
    return 1;
}
#include "terminal_logger.c"
#include "allocator.c"
