from typing import Callable, Optional
ErrorReporter = Optional[Callable[[int, str, int, int, str], None]]
def htmlgen(text:str, base_dir:str='.', error_reporter:ErrorReporter=None) -> str: ...
def reformat(text:str, error_reporter:ErrorReporter=None) -> str: ...
